# Generated by Django 3.2.5 on 2022-12-05 21:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='online course', max_length=180)),
                ('cover', django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.jpg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[600, 400], upload_to='profile/images/%Y/%m/%d', verbose_name='Course Cover Image')),
                ('description', models.TextField()),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='Slug')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('courseprice', models.DecimalField(decimal_places=2, default=10000, max_digits=10, verbose_name='Course Price')),
                ('points', models.IntegerField(default=5, verbose_name='GPD Points')),
                ('pub_date', models.DateField(default=datetime.date.today)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Course Author')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('content', models.TextField(verbose_name='What will they learn')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('title', models.CharField(default='title', max_length=200)),
                ('video', models.TextField(verbose_name='Embed video Url')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='courseVideo', to='course.lesson', verbose_name='Course Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='CourseDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='document name', max_length=200)),
                ('document', models.FileField(upload_to=None, verbose_name='Supportind Document')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='courseDocument', to='course.lesson', verbose_name='Course Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Paid Course')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolledcourse', to='course.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL, verbose_name='Course Author')),
            ],
            options={
                'unique_together': {('course', 'student')},
            },
        ),
    ]
