# Generated by Django 3.2.5 on 2022-11-30 14:49

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cover',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.jpg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[600, 400], upload_to='profile/images/%Y/%m/%d', verbose_name='Course Cover Image'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(default='online course', max_length=180),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(verbose_name='What will they learn'),
        ),
    ]
