# Generated by Django 3.2.5 on 2022-12-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='introvidep',
            field=models.TextField(blank=True, default='<iframe width="560" height="315" src="https://www.youtube.com/embed/ddsebipcm7M" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>', null=True),
        ),
    ]
