# Generated by Django 3.2.5 on 2022-11-14 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pub_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
