# Generated by Django 3.2.5 on 2022-11-27 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursevideo',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lesson', verbose_name='Course Lesson'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='course.course'),
        ),
        migrations.CreateModel(
            name='CourseDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to=None, verbose_name='Supportind Document')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseDocument', to='course.lesson', verbose_name='Course Lesson')),
            ],
        ),
    ]
