# Generated by Django 3.2.5 on 2022-11-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursevideo',
            name='video',
            field=models.TextField(verbose_name='Embed video Url'),
        ),
    ]
