# Generated by Django 3.2.5 on 2023-02-05 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_rename_introvidep_course_introvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='module',
            field=models.CharField(choices=[('Internal Module', 'Internal Module'), ('Area9 Module', 'Area9 Module'), ('SCORM Module', 'SCORM Module')], default='Internal Module', max_length=50, verbose_name='Type od module'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.CreateModel(
            name='AreaNineModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduleLink', models.URLField(max_length=300, verbose_name='Module Link from area 9 or any platform')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='Module')),
            ],
        ),
    ]
