# Generated by Django 3.2.5 on 2022-11-27 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20221127_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedocuments',
            name='lesson',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='courseDocument', to='course.lesson', verbose_name='Course Lesson'),
        ),
        migrations.AlterField(
            model_name='coursevideo',
            name='lesson',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course.lesson', verbose_name='Course Lesson'),
        ),
    ]
