# Generated by Django 3.2.5 on 2022-12-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_coursevideo_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedocuments',
            name='title',
            field=models.CharField(default='document name', max_length=200),
        ),
    ]
