# Generated by Django 3.2.5 on 2023-02-07 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20230205_1519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areaninemodule',
            options={'verbose_name': 'Area Nine Module', 'verbose_name_plural': 'Area Nine Modules'},
        ),
        migrations.AlterField(
            model_name='areaninemodule',
            name='module',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coursemodule', to='course.course', verbose_name='Module'),
        ),
    ]
