# Generated by Django 3.2.5 on 2022-12-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_coursedocuments_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='points',
            field=models.IntegerField(default=5, verbose_name='GPD Points'),
        ),
    ]
