# Generated by Django 3.2.5 on 2022-12-08 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='discussions.topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(editable=False, unique=True, verbose_name='URL slug'),
        ),
    ]
